### ISSUE TITLE
Mobile SCSS

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/website2.0#20]
Needs to look more practical on mobile

**Comment by Sean1572** [comment]
![image](https://github.com/UCSD-E4E/website2.0/assets/25123131/6d3b8362-96e3-46a7-88ed-f5b875a32465)

**Comment by Sean1572** [comment]
Notes on site
- Archive seems fine, the year at the bottom looks weird but its functional 
- about page, professor bios are strange, consider allowing it to go vertically on mobile
- calendar is almost fine, clicking on an event opens a popup that may go over the screen
- project pages look good on quick glance
- contact look good
- peoples pages look good
- expeditions look good
- publications may benefit from collapsible abstracts but passable
- open ops look good
- Welcome page is fine, might need to look into why not all photos are center-aligned on mobile (most likely flexbox?)
- video iframes need to be reviewed: they often are set sizes that do not scale with page

All in all, doesn't seem terrible. Main thing is frontpage + nav bar. Once those are better then mobile is useable

**Comment by Sean1572** [comment]
![image](https://github.com/UCSD-E4E/website2.0/assets/25123131/234262dc-8561-4adc-ae40-e2c1ebfb8e40)
Current new look for nav bar. Make sure to test both in mobile and on desktop to ensure both are working as intended
